WEB_API_MVC/Homework_8-9/Controllers/UserActionLogsController.cs
using Homework_8_9.Helpers;
using Homework_8_9.Models;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace Homework_8_9.Controllers
{
    [CustomAuthorize(Roles = "Admin")]
    public class UserActionLogsController : WebsiteControllerBase
    {
        public async Task<ActionResult> Index()
        {
            var ViewModel = await UserActionLogsModel.GetPageViewModel();
            return View(ViewModel);
        }
    }
}

WEB_API_MVC/Homework_8-9/Views/Shared/_Layout.cshtml
@{ var Model = (Homework_8_9.Models.WebsiteLayoutViewModel)ViewData["ConstantsViewDataLayoutViewModel"]; }
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Simple Shop", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("About", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    @if (Model.IsAdmin)
                    {
                    <li>@Html.ActionLink("Logs", "Index", "UserActionLogs", new { area = "" }, new { @class = "nav-link" })</li>
                    }
                </ul>

                @if (Model.IsAuthenticated)
                {
                    using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
                    {
                        @Html.AntiForgeryToken()

                        <ul class="navbar-nav navbar-right">
                            <li>
                                @Html.ActionLink("Hello " + Model.User.Email + "!", "Index", "Manage", routeValues: null, htmlAttributes: new { title = "Manage", @class = "nav-link" })
                            </li>
                            <li><a class="nav-link" href="javascript:document.getElementById('logoutForm').submit()">Log off</a></li>
                        </ul>
                    }
                }
                else
                {
                    <ul class="navbar-nav navbar-right">
                        <li>@Html.ActionLink("Register", "Register", "Account", routeValues: null, htmlAttributes: new { id = "registerLink", @class = "nav-link" })</li>
                        <li>@Html.ActionLink("Log in", "Login", "Account", routeValues: null, htmlAttributes: new { id = "loginLink", @class = "nav-link" })</li>
                    </ul>
                }

            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>